CREATE TABLE "security".organization (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	address varchar(255) NULL,
	address2 varchar(255) NULL,
	city varchar(255) NULL,
	country varchar(255) NULL,
	"name" varchar(255) NULL,
	postalcode varchar(255) NULL,
	state varchar(255) NULL,
	CONSTRAINT organization_pkey PRIMARY KEY (id)
);

INSERT INTO "security".organization (address,address2,city,country,"name",postalcode,state) VALUES
	 ('100 1st AVE',NULL,'Cincinnati','USA','Penny Technologies','45244','OH');
