CREATE TABLE "security"."role" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT role_pkey PRIMARY KEY (id)
);
insert into "security".role (name) values('OrgUser');
insert into "security".role (name) values('OrgAdmin');
insert into "security".role (name) values('SuperUser');