CREATE TABLE "security"."user" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email varchar(255) NULL,
	"name" varchar(255) NULL,
	default_workspace_id int8 NULL,
	organization_id int8 NULL,
	role_id int8 NULL,
	"password" varchar(255) NULL,
	CONSTRAINT user_pkey PRIMARY KEY (id)
);
ALTER TABLE "security"."user" ADD CONSTRAINT "FK47s23cxhafnkyhcnfgpwg9qeq" FOREIGN KEY (default_workspace_id) REFERENCES "security".workspace(id);
ALTER TABLE "security"."user" ADD CONSTRAINT "FK9usot4gododq1u90duvulb92d" FOREIGN KEY (role_id) REFERENCES "security"."role"(id);
ALTER TABLE "security"."user" ADD CONSTRAINT "FKdoir9r27qpdmycnkpamjawo4e" FOREIGN KEY (organization_id) REFERENCES "security".organization(id);

INSERT INTO "security"."user" (email,"name",default_workspace_id,organization_id,role_id,"password") VALUES
	 ('raghu.porumamilla@gmail.com','Raghu Porumamilla',1,1,1,'$2a$10$FXqs6EVGQ.F14teFQuoEHe30QnhyPcK0cWF2P5vWlhRrmJ9I1kDUq');
