CREATE TABLE "security".workspace (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	organization_id int8 NULL,
	CONSTRAINT workspace_pkey PRIMARY KEY (id)
);

ALTER TABLE "security".workspace ADD CONSTRAINT fkk4q3bjw51dov0jcxo2ngtorfr FOREIGN KEY (organization_id) REFERENCES "security".organization(id);

INSERT INTO "security".workspace (name,organization_id) VALUES
	 ('Dev',1);