-- "event"."source" definition

-- Drop table

-- DROP TABLE "event"."source";

CREATE TABLE "event"."source" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	"type" varchar(255) NULL,
	org_id int8 NULL,
	workspace_id int8 NULL,
	CONSTRAINT source_pkey PRIMARY KEY (id),
	CONSTRAINT source_type_check CHECK (((type)::text = ANY ((ARRAY['API'::character varying, 'SALESFORCE'::character varying])::text[])))
);


-- "event"."source" foreign keys

ALTER TABLE "event"."source" ADD CONSTRAINT "FKegfr69i9kec336gafs3t0bcem" FOREIGN KEY (org_id) REFERENCES "security".organization(id);
ALTER TABLE "event"."source" ADD CONSTRAINT "FKlua11ikv0wrm1uonr6s19d1v3" FOREIGN KEY (workspace_id) REFERENCES "security".workspace(id);

INSERT INTO "event"."source"
(id, "name", "type", org_id, workspace_id)
VALUES(1, 'Generic API', 'API', 1, 1);
