-- "event"."target" definition

-- Drop table

-- DROP TABLE "event"."target";

CREATE TABLE "event"."target" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	"type" varchar(255) NULL,
	org_id int8 NULL,
	workspace_id int8 NULL,
	CONSTRAINT target_pkey PRIMARY KEY (id),
	CONSTRAINT target_type_check CHECK (((type)::text = ANY ((ARRAY['BIGQUERY'::character varying, 'API'::character varying, 'JDBC'::character varying])::text[])))
);


-- "event"."target" foreign keys

ALTER TABLE "event"."target" ADD CONSTRAINT "FKets2wsyyyetulbatuvkioemd0" FOREIGN KEY (workspace_id) REFERENCES "security".workspace(id);
ALTER TABLE "event"."target" ADD CONSTRAINT "FKju2gm4u7v41k5gudenin285d5" FOREIGN KEY (org_id) REFERENCES "security".organization(id);


INSERT INTO "event"."target"
(id, "name", "type", org_id, workspace_id)
VALUES(1, 'DataWarehouse', 'BIGQUERY', 1, 1);