-- "event".event_definition definition

-- Drop table

-- DROP TABLE "event".event_definition;

CREATE TABLE "event".event_definition (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"eventName" varchar(255) NULL,
	payload_schema text NULL,
	organization_id int8 NULL,
	source_id int8 NULL,
	workspace_id int8 NULL,
	"payloadSchema" varchar(255) NULL,
	CONSTRAINT event_definition_pkey PRIMARY KEY (id)
);


-- "event".event_definition foreign keys

ALTER TABLE "event".event_definition ADD CONSTRAINT "FK5iwcmb2hiymprvd1p4kyjcjn8" FOREIGN KEY (organization_id) REFERENCES "security".organization(id);
ALTER TABLE "event".event_definition ADD CONSTRAINT "FKfep1uefmb7m9t7p3im9ymv18p" FOREIGN KEY (workspace_id) REFERENCES "security".workspace(id);
ALTER TABLE "event".event_definition ADD CONSTRAINT "FKmx25k047r7usxstbfavq212vy" FOREIGN KEY (source_id) REFERENCES "event"."source"(id);

INSERT INTO "event".event_definition
(id, "eventName", payload_schema, organization_id, source_id, workspace_id, "payloadSchema")
VALUES(1, 'SoilSensorEvent', '{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "SoilSensorPayload",
  "type": "object",
  "required": ["metadata", "readings", "device_health"],
  "properties": {
    "metadata": {
      "type": "object",
      "required": ["sensor_id", "timestamp", "location"],
      "properties": {
        "sensor_id": { "type": "string" },
        "timestamp": { "type": "string", "format": "date-time" },
        "location": {
          "type": "object",
          "properties": {
            "lat": { "type": "number", "minimum": -90, "maximum": 90 },
            "lon": { "type": "number", "minimum": -180, "maximum": 180 }
          }
        }
      }
    },
    "readings": {
      "type": "object",
      "required": ["moisture", "soil_temp", "ph_level"],
      "properties": {
        "moisture": {
          "type": "object",
          "properties": {
            "value": { "type": "number", "minimum": 0, "maximum": 100 },
            "unit": { "type": "string", "const": "%" }
          }
        },
        "soil_temp": {
          "type": "object",
          "properties": {
            "value": { "type": "number" },
            "unit": { "type": "string", "enum": ["°C", "°F"] }
          }
        },
        "ph_level": {
          "type": "object",
          "properties": {
            "value": { "type": "number", "minimum": 0, "maximum": 14 }
          }
        },
        "nutrients": {
          "type": "object",
          "properties": {
            "nitrogen": { "type": "integer" },
            "phosphorus": { "type": "integer" },
            "potassium": { "type": "integer" }
          }
        }
      }
    },
    "device_health": {
      "type": "object",
      "properties": {
        "battery_level": { "type": "integer", "minimum": 0, "maximum": 100 },
        "signal_strength": { "type": "integer" }
      }
    }
  }
}', 1, 1, 1, NULL);