-- "event"."event" definition

-- Drop table

-- DROP TABLE "event"."event";

CREATE TABLE "event"."event" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	payload text NULL,
	"timestamp" varchar(255) NULL,
	event_definition_id int8 NULL,
	organization_id int8 NULL,
	source_id int8 NULL,
	workspace_id int8 NULL,
	CONSTRAINT event_pkey PRIMARY KEY (id)
);


-- "event"."event" foreign keys

ALTER TABLE "event"."event" ADD CONSTRAINT "FK2qwb7q4p5pdqyds1dt0hicdxa" FOREIGN KEY (event_definition_id) REFERENCES "event".event_definition(id);
ALTER TABLE "event"."event" ADD CONSTRAINT "FK5rkm977o3k9h03tbm8y1mc43r" FOREIGN KEY (source_id) REFERENCES "event"."source"(id);
ALTER TABLE "event"."event" ADD CONSTRAINT "FK61qckwmtp137r1slg1y69qpug" FOREIGN KEY (organization_id) REFERENCES "security".organization(id);
ALTER TABLE "event"."event" ADD CONSTRAINT "FKmii8aswxskoh3qqhr4uamalkh" FOREIGN KEY (workspace_id) REFERENCES "security".workspace(id);

INSERT INTO "event"."event"
(id, "name", payload, "timestamp", event_definition_id, organization_id, source_id, workspace_id)
VALUES(6, NULL, '{
  "metadata": {
    "sensor_id": "SOIL-PROBE-4492",
    "timestamp": "2026-01-18T14:30:00Z",
    "location": {
      "lat": 41.8781,
      "lon": -87.6298
    },
    "firmware_version": "v2.1.4"
  },
  "readings": {
    "moisture": {
      "value": 24.5,
      "unit": "%",
      "status": "optimal"
    },
    "soil_temp": {
      "value": 18.2,
      "unit": "°C"
    },
    "conductivity": {
      "value": 1.2,
      "unit": "mS/cm",
      "description": "EC"
    },
    "ph_level": {
      "value": 6.8,
      "unit": "pH"
    },
    "nutrients": {
      "nitrogen": 45,
      "phosphorus": 12,
      "potassium": 38,
      "unit": "mg/kg"
    }
  },
  "device_health": {
    "battery_level": 88,
    "signal_strength": -92,
    "solar_charging": true
  }
}', '2026-01-19 10:41:50.206136-05', 1, 1, 1, 1);